### PR TITLE
Make main error more readable

### PR DESCRIPTION
**Pull request by jspeed-meyers**
This original error message confused me. This is a proposed replacement. I'm also a novice Go programmer though :)

### CODE REVIEW

**Comment by houdini91** [comment]
I think the place to document the go env is some kind of dev.md or some subsection in our readme rather than the logs which will be part of the protobom binary.

**Comment by puerco** [comment]
@houdini91 which go env?

**Comment by houdini91** [comment]
> @houdini91 which go env?

I mean having a log printing the golang command is part of the golang development environment

**Comment by jspeed-meyers** [comment]
I'll close this and open up a separate issue to create a development.MD file.

**Pull request closed without merging**
