### PR TITLE
Add PDF of SBOM format translation library proposal

### PR DESCRIPTION
**Pull request by jspeed-meyers**
Related to issue #56 

Outstanding questions: What format? PDF? Something else? PDF is convenient for representing the document without changing it. But it's bad for version control. Also, where to put this document within the file structure?

Alternatively, we could create a separate repo for design documents. Thoughts?

### CODE REVIEW

**Comment by puerco** [comment]
I think we should distill this into a markdown file and store it in `docs/design/` or similar. I prefer if we can spare the download of the PDF to developers every time someone imports the library. We can still host the PDF on github (upload as if it was an image) and link it. Or in a gist, just not checked into git. WDYT?

**Comment by veramine** [comment]
I agree

**Comment by jspeed-meyers** [comment]
@puerco and @veramine: sounds good. @puerco, can you please then distill this into a markdown file and store it in `docs/design/`?

**Comment by veramine** [comment]
I created a new pull request with a MD + the two images.

**Review by veramine — CHANGES_REQUESTED** [review]
Agree we should use markdown, see new PR

**Comment by jspeed-meyers** [comment]
Closing this PR. Thank you, @veramine!

**Pull request closed without merging**
